# State store
STATE_DB="db_entity_matching_state_store"
STATE_TABLE="entity_matching_job_states"

# State columns
STATE_STATUS="STATUS"
STATE_ID="ID"
STATE_MATCHING_JOB_ID="MATCHING_JOB_ID"
STATE_MODEL_ID="MODEL_ID"
STATE_SOURCE_CREATED_TIME="SOURCE_CREATED_TIME"
STATE_SOURCE_UPDATED_TIME="SOURCE_UPDATED_TIME"
STATE_SOURCE_CREATED_USER="SOURCE_CREATED_USER"
STATE_SOURCE_UPDATED_USER="SOURCE_UPDATED_USER"
STATE_INTERVAL="INTERVAL"
STATE_CONFIG="CONFIG"

# Getting Instances
SOURCE="SOURCE"
TARGET="TARGET"